export const columnMappings = {
    version_name: "Versión",
    brand_name: "Marca",
    title: "Título",
    description: "Descripción",
    gender: "Género",
    status: "Estado",
    createdAt: "Fecha de Creación",
    updatedAt: "Última Actualización",
    version_id_fk: 'Versión',
    brand_id_fk: 'Marca',
    align: 'Alineación',
    parfum_img: 'Imagen de Perfume',
    back_img: 'Imagen de Fondo',
    url: 'URL',
    color: 'Color',
    color2: 'Color 2',
    parfum_id_fk: 'Perfume',
    ml: "Mililitros",
    img: "Imagen",
    cost: 'Precio Costo',
    price: "Precio de Nosotros",
    seller_profit: "Ganancia del Vendedor",
    old_price: "Precio al Público",
    type_of_sale: "Tipo de Venta",
    price_flash: "Precio Flash",
    flash_seller_profit: "Ganancia del Vendedor en Venta Flash",
    quantity_flash: 'Cantidad Flash',
    firstname: 'Nombre',
    lastname: 'Apellido',
    email: 'Email',
    rol: 'Rol',
    userName: 'Nombre',
    phone: 'Teléfono',
    direction: 'Dirección',
    subTotal: 'SubTotal',
    total: 'Total',
    products: 'Productos',
    productsTypes: 'Tipos',
    quantities: 'Cantidades',
    code: 'Código',
    percentage: 'Porcentaje'
    // Agrega más columnas si es necesario
  };

  export const excludedColumns = ["_id", "__v", "updatedAt", "url"];
  export const excludedColumnsSeller = ["_id", "__v", "updatedAt", "url", "createdAt"];
